services:
  backend:
    build: ./backend
    container_name: shopee_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: Shopee
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopee
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - shopee-network
    depends_on: 
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: shopee_frontend
    ports:
      - "3000:80"
    networks:
      - shopee-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopee
      MYSQL_USER: senac
      MYSQL_PASSWORD: senac
    ports:
      - "4306:3306"
    networks:
      - shopee-network

networks:
  shopee-network:
    driver: bridge
