services:
  backend:
    build: ./backend
    container_name: shopee_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      SPRING_APPLICATION_NAME: Shopee
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - shopee-network
    depends_on: 
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: shopee_frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    networks:
      - shopee-network
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - shopee-network
    env_file:
      - ./backend/.env

networks:
  shopee-network:
    driver: bridge
