FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY backend/src ./src

COPY backend/pom.xml .

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
# teste
ENTRYPOINT [ "java", "-jar", "/app/app.jar" ]