# Imagem base com Maven e JDK 17
FROM maven:3.8.4-openjdk-17 AS build  

# Define o diretório de trabalho
WORKDIR /app  

# Copia o arquivo pom.xml para o contêiner
COPY pom.xml .  

# Copia o código-fonte para o contêiner
COPY src ./src  

# Compila o projeto sem rodar testes
RUN mvn clean package -DskipTests  

# Imagem base para o runtime
FROM openjdk:17-jdk-alpine  

# Define o diretório de trabalho
WORKDIR /app  

# Copia o arquivo JAR gerado para o contêiner
COPY --from=build /app/target/*.jar app.jar  

# Expõe a porta 8080
EXPOSE 8080  

# Comando para iniciar a aplicação
ENTRYPOINT [ "java", "-jar", "/app/app.jar" ]  